package com.company.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public class StatementSpy implements Statement {

	protected Statement realStatement;

	public StatementSpy(final Statement realStatement) {
		super();
		this.realStatement = realStatement;
	}

	@Override
	public void addBatch(final String sql) throws SQLException {
		realStatement.addBatch(sql);
	}

	@Override
	public void cancel() throws SQLException {
		realStatement.cancel();
	}

	@Override
	public void clearBatch() throws SQLException {
		realStatement.clearBatch();
	}

	@Override
	public void clearWarnings() throws SQLException {
		realStatement.clearWarnings();
	}

	@Override
	public void close() throws SQLException {
		realStatement.close();
	}

	@Override
	public boolean execute(final String sql) throws SQLException {
		return realStatement.execute(sql);
	}

	@Override
	public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
		return realStatement.execute(sql, autoGeneratedKeys);
	}

	@Override
	public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
		return realStatement.execute(sql, columnIndexes);
	}

	@Override
	public boolean execute(final String sql, final String[] columnNames) throws SQLException {
		return realStatement.execute(sql, columnNames);
	}

	@Override
	public int[] executeBatch() throws SQLException {
		return realStatement.executeBatch();
	}

	@Override
	public ResultSet executeQuery(final String sql) throws SQLException {
		final ResultSet realResultSet = realStatement.executeQuery(sql);
		return new ResultSetSpy(realResultSet);
	}

	@Override
	public int executeUpdate(final String sql) throws SQLException {
		return realStatement.executeUpdate(sql);
	}

	@Override
	public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
		return realStatement.executeUpdate(sql, autoGeneratedKeys);
	}

	@Override
	public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
		return realStatement.executeUpdate(sql, columnIndexes);
	}

	@Override
	public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
		return realStatement.executeUpdate(sql, columnNames);
	}

	@Override
	public Connection getConnection() throws SQLException {
		return realStatement.getConnection();
	}

	@Override
	public int getFetchDirection() throws SQLException {
		return realStatement.getFetchDirection();
	}

	@Override
	public int getFetchSize() throws SQLException {
		return realStatement.getFetchSize();
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		final ResultSet realResultSet = realStatement.getGeneratedKeys();
		return new ResultSetSpy(realResultSet);
	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		return realStatement.getMaxFieldSize();
	}

	@Override
	public int getMaxRows() throws SQLException {
		return realStatement.getMaxRows();
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		return realStatement.getMoreResults();
	}

	@Override
	public boolean getMoreResults(final int current) throws SQLException {
		return realStatement.getMoreResults(current);
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		return realStatement.getQueryTimeout();
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		final ResultSet realResultSet = realStatement.getResultSet();
		return new ResultSetSpy(realResultSet);
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		return realStatement.getResultSetConcurrency();
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		return realStatement.getResultSetHoldability();
	}

	@Override
	public int getResultSetType() throws SQLException {
		return realStatement.getResultSetType();
	}

	@Override
	public int getUpdateCount() throws SQLException {
		return realStatement.getUpdateCount();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return realStatement.getWarnings();
	}

	@Override
	public boolean isClosed() throws SQLException {
		return realStatement.isClosed();
	}

	@Override
	public boolean isPoolable() throws SQLException {
		return realStatement.isPoolable();
	}

	@Override
	public boolean isWrapperFor(final Class<?> iface) throws SQLException {
		return realStatement.isWrapperFor(iface);
	}

	@Override
	public void setCursorName(final String name) throws SQLException {
		realStatement.setCursorName(name);
	}

	@Override
	public void setEscapeProcessing(final boolean enable) throws SQLException {
		realStatement.setEscapeProcessing(enable);
	}

	@Override
	public void setFetchDirection(final int direction) throws SQLException {
		realStatement.setFetchDirection(direction);
	}

	@Override
	public void setFetchSize(final int rows) throws SQLException {
		realStatement.setFetchSize(rows);
	}

	@Override
	public void setMaxFieldSize(final int max) throws SQLException {
		realStatement.setMaxFieldSize(max);
	}

	@Override
	public void setMaxRows(final int max) throws SQLException {
		realStatement.setMaxRows(max);
	}

	@Override
	public void setPoolable(final boolean poolable) throws SQLException {
		realStatement.setPoolable(poolable);
	}

	@Override
	public void setQueryTimeout(final int seconds) throws SQLException {
		realStatement.setQueryTimeout(seconds);
	}

	@Override
	public <T> T unwrap(final Class<T> iface) throws SQLException {
		return realStatement.unwrap(iface);
	}

}
